### ISSUE TITLE
运行一段时间后出现报错并无法生成文转图

### ISSUE THREAD

**Issue by axlmly** [koishijs/koishi-plugin-imagify#8]
日志
2024-08-06 08:21:26 [E] imagify ProtocolError: Page.captureScreenshot timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
                            at <instance_members_initializer> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:93:14)
                            at new Callback (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:97:16)
                            at CallbackRegistry.create (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:22:26)
                            at Connection._rawSend (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:88:26)
                            at CdpCDPSession.send (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\CDPSession.js:66:33)
                            at CdpPage._screenshot (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Page.js:798:62)
                            at CdpPage.screenshot (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:1089:41)
                            at async CdpPage.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\util\decorators.js:164:24)
                            at async screenShotPage (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-imagify\lib\index.js:208:28)
                            at async Proxy.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-imagify\lib\index.js:217:31)
2024-08-06 08:21:26 [W] session TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
                            at Function.from (node:buffer:319:9)
                            at Proxy.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-imagify\lib\index.js:228:61)
                            at async Proxy.serial (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:500:22)
                            at async OneBotMessageEncoder.send (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:613:9)
                            at async Proxy.sendMessage (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:346:22)
2024-08-06 08:24:26 [E] imagify ProtocolError: Page.captureScreenshot timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
                            at <instance_members_initializer> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:93:14)
                            at new Callback (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:97:16)
                            at CallbackRegistry.create (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:22:26)
                            at Connection._rawSend (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:88:26)
                            at CdpCDPSession.send (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\CDPSession.js:66:33)
                            at CdpPage._screenshot (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Page.js:798:62)
                            at CdpPage.screenshot (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:1089:41)
                            at async CdpPage.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\util\decorators.js:164:24)
                            at async screenShotPage (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-imagify\lib\index.js:208:28)
                            at async Proxy.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-imagify\lib\index.js:217:31)
2024-08-06 08:24:26 [W] session TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
                            at Function.from (node:buffer:319:9)
                            at Proxy.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-imagify\lib\index.js:228:61)
                            at async Proxy.serial (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:500:22)
                            at async OneBotMessageEncoder.send (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:613:9)
                            at async Proxy.sendMessage (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:346:22)
                            at async C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2172:7
                            at async Proxy.withScope (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2069:22)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
2024-08-06 08:27:30 [E] imagify ProtocolError: Page.captureScreenshot timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
                            at <instance_members_initializer> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:93:14)
                            at new Callback (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:97:16)
                            at CallbackRegistry.create (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:22:26)
                            at Connection._rawSend (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:88:26)
                            at CdpCDPSession.send (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\CDPSession.js:66:33)
                            at CdpPage._screenshot (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Page.js:798:62)
                            at CdpPage.screenshot (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:1089:41)
                            at runNextTicks (node:internal/process/task_queues:60:5)
                            at process.processImmediate (node:internal/timers:449:9)
                            at async CdpPage.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\util\decorators.js:164:24)
2024-08-06 08:27:30 [W] session TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
                            at Function.from (node:buffer:319:9)
                            at Proxy.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-imagify\lib\index.js:228:61)
                            at async Proxy.serial (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:500:22)
                            at async OneBotMessageEncoder.send (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:613:9)
                            at async Proxy.sendMessage (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:346:22)
                            at async C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2172:7
                            at async Proxy.withScope (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2069:22)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
2024-08-06 08:30:30 [E] imagify ProtocolError: Page.captureScreenshot timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
                            at <instance_members_initializer> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:93:14)
                            at new Callback (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:97:16)
                            at CallbackRegistry.create (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:22:26)
                            at Connection._rawSend (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:88:26)
                            at CdpCDPSession.send (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\CDPSession.js:66:33)
                            at CdpPage._screenshot (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Page.js:798:62)
                            at CdpPage.screenshot (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:1089:41)
                            at async CdpPage.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\util\decorators.js:164:24)
                            at async screenShotPage (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-imagify\lib\index.js:208:28)
                            at async Proxy.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-imagify\lib\index.js:217:31)
2024-08-06 08:30:30 [W] session TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
                            at Function.from (node:buffer:319:9)
                            at Proxy.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-imagify\lib\index.js:228:61)
                            at async Proxy.serial (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:500:22)
                            at async OneBotMessageEncoder.send (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:613:9)
                            at async Proxy.sendMessage (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:346:22)
                            at async C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2172:7
                            at async Proxy.withScope (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2069:22)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
2024-08-06 09:00:10 [W] booru source lolibooru request failed 
2024-08-06 11:24:19 [I] cr 推送动态中，使用render模式
2024-08-06 12:04:00 [E] cr liveDetect getLiveRoomInfo 发生了错误，错误为：网络异常，本次请求失败！
2024-08-06 12:11:06 [E] imagify ProtocolError: Page.captureScreenshot timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
                            at <instance_members_initializer> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:93:14)
                            at new Callback (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:97:16)
                            at CallbackRegistry.create (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:22:26)
                            at Connection._rawSend (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:88:26)
                            at CdpCDPSession.send (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\CDPSession.js:66:33)
                            at CdpPage._screenshot (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Page.js:798:62)
                            at CdpPage.screenshot (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:1089:41)
                            at async CdpPage.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\util\decorators.js:164:24)
                            at async screenShotPage (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-imagify\lib\index.js:208:28)
                            at async Proxy.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-imagify\lib\index.js:217:31)
2024-08-06 12:11:06 [W] session TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
                            at Function.from (node:buffer:319:9)
                            at Proxy.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-imagify\lib\index.js:228:61)
                            at async Proxy.serial (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:500:22)
                            at async OneBotMessageEncoder.send (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:613:9)
                            at async Proxy.sendMessage (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:346:22)
                            at async C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2172:7
                            at async Proxy.withScope (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2069:22)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
                            at async next (C:\Users\xiuzh\AppData\Roaming\

imagify版本2.2.7

**Comment by Lipraty** [comment]
请提供一下插件配置截图。

**Comment by axlmly** [comment]
> 请提供一下插件配置截图。

之前是这样的![Screenshot_2024-08-13-10-20-58-276_com.android.chrome.jpg](https://github.com/user-attachments/assets/17bf12cd-bd94-4620-9082-23422dfbd059)

**Comment by Lipraty** [comment]
尝试解决该问题并已发布 `2.2.8` 版本，你可以更新下看看有没有解决。
